### PR TITLE
Refactor save_avio_options to common location for use by imf, hls and dash decoders

### PR DESCRIPTION
**Pull request by nvanderzwet-ssimwave**
In response to
https://github.com/sandflow/ffmpeg-imf/commit/1ef114743d370bd7c59a2f6a8e77bf6c03b70bf5#commitcomment-61522771

### CODE REVIEW

**Comment by nvanderzwet-ssimwave** [comment]
fixing build issue now, missing include

**Comment by palemieux** [comment]
@nvanderzwet-ssimwave Looks good. I think we should first submit a standalone patch against `libavformat/avio_internal.h`, `libavformat/aviobuf.c`,  `libavformat/dashdec.c` and `libavformat/hls.c`. Happy to do it, unless you prefer to.

**Comment by palemieux** [comment]
Submitted at http://ffmpeg.org/pipermail/ffmpeg-devel/2021-December/289689.html

**Comment by palemieux** [comment]
See http://ffmpeg.org/pipermail/ffmpeg-devel/2021-December/289768.html for status

**Comment by nvanderzwet-ssimwave** [comment]
> See http://ffmpeg.org/pipermail/ffmpeg-devel/2021-December/289768.html for status

**Pull request closed without merging**
